# Generated by Django 3.2.7 on 2022-01-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_prices',
            new_name='product_price',
        ),
    ]
